In [57]:
import torch
print(torch.__version__)

2.10.0+cpu

In [58]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"GPU name is {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is not available

In [59]:
x = torch.empty(2,3)
print(x)
print(x.type())

tensor([[-5.6135e-37,  4.5403e-41, -5.6154e-37],
        [ 4.5403e-41, -5.6158e-37,  4.5403e-41]])
torch.FloatTensor

In [60]:
print(torch.zeros(2,3))
print(torch.ones(2,3))
print(torch.eye(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [61]:
print(torch.rand(2,3))

tensor([[0.8930, 0.5597, 0.2803],
        [0.2476, 0.4738, 0.1306]])

In [62]:
torch.manual_seed(12)
print(torch.rand(2,3))

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])

In [63]:
torch.manual_seed(12)
torch.rand(2,3)

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])

### Training using PyTorch

In [64]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [65]:
df = pd.read_csv("/content/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [66]:
df.shape

(569, 33)

In [67]:
df = df.drop(columns=["id","Unnamed: 32"])

In [68]:
df.sample(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
170,B,12.32,12.39,78.85,464.1,0.10280,0.06981,0.03987,0.03700,0.1959,...,13.50,15.64,86.97,549.1,0.13850,0.1266,0.1242,0.09391,0.2827,0.06771
298,B,14.26,18.17,91.22,633.1,0.06576,0.05220,0.02475,0.01374,0.1635,...,16.22,25.26,105.80,819.7,0.09445,0.2167,0.1565,0.07530,0.2636,0.07676
119,M,17.95,20.01,114.20,982.0,0.08402,0.06722,0.07293,0.05596,0.2129,...,20.58,27.83,129.20,1261.0,0.10720,0.1202,0.2249,0.11850,0.4882,0.06111
430,M,14.90,22.53,102.10,685.0,0.09947,0.22250,0.27330,0.09711,0.2041,...,16.35,27.57,125.40,832.7,0.14190,0.7090,0.9019,0.24750,0.2866,0.11550
143,B,12.90,15.92,83.74,512.2,0.08677,0.09509,0.04894,0.03088,0.1778,...,14.48,21.82,97.17,643.8,0.13120,0.2548,0.2090,0.10120,0.3549,0.08118

In [69]:
df["diagnosis"] = df["diagnosis"].map({'M':1 ,'B':0})

In [70]:
df.sample(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
207,1,17.01,20.26,109.70,904.3,0.08772,0.07304,0.06950,0.05390,0.2026,...,19.80,25.05,130.00,1210.0,0.1111,0.1486,0.1932,0.10960,0.3275,0.06469
321,1,20.16,19.66,131.10,1274.0,0.08020,0.08564,0.11550,0.07726,0.1928,...,23.06,23.03,150.20,1657.0,0.1054,0.1537,0.2606,0.14250,0.3055,0.05933
361,0,13.30,21.57,85.24,546.1,0.08582,0.06373,0.03344,0.02424,0.1815,...,14.20,29.20,92.94,621.2,0.1140,0.1667,0.1212,0.05614,0.2637,0.06658
515,0,11.34,18.61,72.76,391.2,0.10490,0.08499,0.04302,0.02594,0.1927,...,12.47,23.03,79.15,478.6,0.1483,0.1574,0.1624,0.08542,0.3060,0.06783
453,0,14.53,13.98,93.86,644.2,0.10990,0.09242,0.06895,0.06495,0.1650,...,15.80,16.93,103.10,749.9,0.1347,0.1478,0.1373,0.10690,0.2606,0.07810

### train test split

In [71]:
x = df.drop(columns=["diagnosis"])
y = df["diagnosis"]

In [72]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [73]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [74]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [75]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [76]:
x_test

array([[-0.46649743, -0.13728933, -0.44421138, ..., -0.19435087,
         0.17275669,  0.20372995],
       [ 1.36536344,  0.49866473,  1.30551088, ...,  0.99177862,
        -0.561211  , -1.00838949],
       [ 0.38006578,  0.06921974,  0.40410139, ...,  0.57035018,
        -0.10783139, -0.20629287],
       ...,
       [-0.73547237, -0.99852603, -0.74138839, ..., -0.27741059,
        -0.3820785 , -0.32408328],
       [ 0.02898271,  2.0334026 ,  0.0274851 , ..., -0.49027026,
        -1.60905688, -0.33137507],
       [ 1.87216885,  2.80077153,  1.80354992, ...,  0.7925579 ,
        -0.05868885, -0.09467243]])

In [77]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

### numpy to tensor

In [78]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

### Define model

In [79]:
class simpleNN():

  def __init__(self,x):
    self.weights = torch.rand(x.shape[1],1,dtype = torch.float64,requires_grad=True)
    self.bias = torch.rand(1,dtype = torch.float64,requires_grad = True)

  def forward(self,x):
    z = torch.matmul(x,self.weights) + self.bias
    return torch.sigmoid(z)

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [80]:
learning_rate = 0.1
epochs = 25

### Traning pipeline

In [83]:
#create Model
model = simpleNN(x_train_tensor)
model.weights

#define loop(number of epochs)

#forward pass

for epoch in range(epochs):
  y_pred = model.forward(x_train_tensor)
  #loss calculate

  loss = model.loss_function(y_pred,y_train_tensor)
  #backward pass(autograd)

  loss.backward()
  #parameters update(weight and bias)

  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

    #zero grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'epochs:{epoch+1} , loss: {loss.item()}')

epochs:1 , loss: 3.3391671244711074
epochs:2 , loss: 3.209665617301101
epochs:3 , loss: 3.0738571735328595
epochs:4 , loss: 2.9336645079341337
epochs:5 , loss: 2.786929732246611
epochs:6 , loss: 2.638975636003374
epochs:7 , loss: 2.492772108056979
epochs:8 , loss: 2.34538863205736
epochs:9 , loss: 2.201583067849354
epochs:10 , loss: 2.0583556882438674
epochs:11 , loss: 1.9193495066076849
epochs:12 , loss: 1.7855215392446786
epochs:13 , loss: 1.653739603896264
epochs:14 , loss: 1.5293859740571003
epochs:15 , loss: 1.4151244719245413
epochs:16 , loss: 1.314318307826367
epochs:17 , loss: 1.2272680165989416
epochs:18 , loss: 1.153782745301189
epochs:19 , loss: 1.0931145853633366
epochs:20 , loss: 1.0439412039587794
epochs:21 , loss: 1.004484248096997
epochs:22 , loss: 0.9728007405625206
epochs:23 , loss: 0.9470928551304147
epochs:24 , loss: 0.9258752938610989
epochs:25 , loss: 0.9080023843141718

In [84]:
model.bias

tensor([0.3917], dtype=torch.float64, requires_grad=True)

In [86]:
model.weights

tensor([[-0.1691],
        [ 0.0741],
        [-0.2931],
        [ 0.1312],
        [ 0.1288],
        [ 0.0885],
        [-0.4903],
        [-0.3969],
        [ 0.0647],
        [-0.3410],
        [ 0.1035],
        [ 0.2116],
        [ 0.4674],
        [ 0.4756],
        [ 0.1772],
        [-0.0659],
        [-0.0176],
        [ 0.0165],
        [ 0.3955],
        [-0.2604],
        [-0.3350],
        [ 0.1854],
        [ 0.2656],
        [-0.0725],
        [ 0.3906],
        [ 0.2597],
        [-0.1201],
        [-0.0020],
        [ 0.1199],
        [ 0.4552]], dtype=torch.float64, requires_grad=True)

In [88]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6012619137763977